### PR TITLE
Removing duplication of JS + CoffeeScript

### PR DESCRIPTION
**Pull request by jrcryer**
Hi,

I've removed the duplication of JS + CoffeeScript as this isn't needed.  I've also added couple of files to make it easier for others to contribute.

Cheers,

James

### CODE REVIEW

**Comment by jrcryer** [comment]
Also added Travis CI configuration for the project as well.

**Comment by jrcryer** [comment]
Any thoughts on merging this in?

Thanks,

James

**Comment by alappe** [comment]
Hey James,

thank you again for this contribution… sorry that I missed to merge it for a few days, I've been on holiday.

So long
Andy

**Comment by jrcryer** [comment]
No probs :+1: - Cheers for checking this whilst being away!

**Pull request merged**
